let table4_2: Map<number, string[]> = new Map<number, string[]>(
    [
        [1,  ["Each department or nursing unit shall be served by a housekeeping room equipped with a service sink. Departments may share service closets provided the departmental services are compatible. A dedicated housekeeping room shall be provided for the following services: Surgical/Catherization, ICU, NICU, nursery, dietary, renal dialysis and outpatient surgery."]],
        [2,  ["Conventional spouts and controls on hot-and cold-water supplies are acceptable. Aerators are not permitted. Non-aerating laminar flow devices are permitted. Nourishment areas shall have a handwashing fixture in or immediately accessible from the nourishment area, in addition to a nourishment sink."]],
        [3,  ["Scrub sinks shall be located outside of sterile procedure rooms. A minimum of two scrub sinks shall be provided in a surgical unit containing one operating room. Four scrub sinks shall be provided in surgical units containing two operating rooms. One additional scrub sink shall be provided per each additional operating room."]],
        [4,  ["The scrub sink is in addition to the required number for surgeries."]],
        [5,  ["The following fixtures shall be provided in airborne infection or protective environment rooms of hospitals only:", "a. Within an adjoining toilet room, a lavatory, a shower containing a seat or a space for a shower chair, and toilet equipped with bedpan flushing attachment with a vacuum breaker.", "b. A handwashing fixture within a separate anteroom."]],
        [6,  ["The following fixtures shall be provided in isolation rooms of correctional treatment centers only:", "a. Within an adjoining toilet area, a handwashing fixture, a shower containing a seat or a space for a shower chair, and water closet equipped with bedpan flushing attachment with a vacuum breaker.", "b. A handwashing fixture within a separate anteroom."]],
        [7,  ["Includes burn center spaces, acute respiratory-care service spaces, and coronary-care service spaces."]],
        [8,  ["A toilet room with handwashing fixture shall directly adjoin each procedure room."]],
        [9,  ["One toilet with lavatory and one shower may serve two labor rooms."]],
        [10, ["One additional scrub sink for each additional cesarean or delivery operating room."]],
        [11, ["Provide emergency eye-wash and shower."]],
        [12, ["Conveniently located for staff use."]],
        [13, ["Fixtures serving individual patient rooms shall not be considered as meeting the required ratios for bedrooms not served by individual adjoining toilet or bathrooms."]],
        [14, ["The clinic sink may be deleted if all bedrooms in the nursing unit are provided with adjoining toilets with bedpan flushing devices."]],
        [15, ["Conventional controls on hot-and cold-water supplies are acceptable. The water discharge points shall be 5 inches (127 millimeters) above the fixture rim. Aerators are not permitted. Non-aerating laminar flow devices are permitted."]],
        [16, ["A minimum of one bathtub is required on each floor of an acute care or acute psychiatric hospital providing skilled nursing or intermediate care services. Special bathing facilities/gurney shower shall be provided at a minimum ratio of one per 100 beds for acute care facilities."]],
        [17, ["In a multiple-bed room, every bed position shall be within 20 feet (6 meters) of a hands-free handwashing fixture. Where an individual room concept is used, a handwashing fixture shall be provided within each infant care room."]],
        [18, ["When three or more procedure rooms are provided."]],
        [19, ["If a separate medicine room is provided, the room shall be equipped with a sink in addition to the nurses' station handwashing fixture. Hot-water supplies are optional."]],
        [20, ["Not required when there is a handwash fixture in the patient bed room."]],
        [21, ["Handwashing fixtures may be deleted if room is used for storage and holding only."]],
        [22, ["If room is used only for temporary holding of soiled materials, clinic sink and work counter may be omitted. If the flushing-rim clinical sink is eliminated, facilities for cleaning bedpans shall be provided elsewhere."]],
        [23, ["Toilet shall be equipped with a bedpan flushing attachment."]],
        [24, ["Optional services approved by the licensing agency shall comply with the applicable space requirements of OSHPD 1 and 2."]],
        [25, ["Shall be provided in each separate room where open medication is handled."]],
        [26, ["Conveniently accessible throughout the unit."]],
        [27, ["Includes rooms or areas within coronary and intensive-care units and postanethesia recovery rooms."]],
        [28, ["Modular toilet/sink combination units located within a privacy curtain may be used within individual patient space or private room. The toilet fixture shall be completely contained within cabinetry when not in use, and shall be enclosed when flushed. Bedpan washers shall not be permitted in patient bedrooms."]],
        [29, ["In service spaces with procedure rooms that do not have dedicated patient toilets, provide a minimum of one patient toilet room with a separate handwashing fixture within the service space."]],
        [30, ["Toilet room shall be accessible from the procedure room."]],
        [31, ["Scrub sink shall be located outside the staff entrance to the procedure room."]],
        [32, ["Not used."]],
        [33, ["Handwashing and scrub sink fixtures shall not be equipped with wrist or elbow blades but shall be equipped with sensor controls, or controls that do not involve contact with the upper extremities."]],
        [34, ["If room is used only for temporary holding of soiled material, clinic sink and work counter may be omitted."]],
        [35, ["A minimum of one separate accessible toilet room shall be provided for the use of patients. Patient toilet room(s) shall be equipped with a handwashing fixture and shall be accessible to the observation units(s) from the corridor. Reference CBC, Part 2, Section 1224.39.6."]],
    ]
);